version: '3'

services:
  nodejs:
    image: cyphrim/nodejs
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DOMAIN: http://localhost:443
        GUN_DOMAIN: http://localhost:443

  nginx:
    depends_on:
      - nodejs
    image: cyphrim/nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "443:443"
