version: '3'

services:
  nodejs:
    image: cyphrim/nodejs
    environment:
      APP_DOMAIN: http://localhost:443
      GUN_DOMAIN: http://localhost:443
    build:
      context: .
      dockerfile: Dockerfile

  nginx:
    depends_on:
      - nodejs
    image: cyphrim/nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "443:443"
